#!/bin/bash
#PBS -N diff
#PBS -l nodes=1:ppn=15
#PBS -o diff.out
#PBS -e diff.out
#PBS -l walltime=240:0:0
#PBS -q high
cd /public/home/jyli/NCBI_SRA/Chew_cotton
cuffmerge -p 10 -g /public/home/jyli/Public_data/Gb.final.all.gene.model.v5.gff3 -s /public/home/jyli/Public_data/GbV1.fasta -o merge89_76 assemble.txt
cuffdiff -o diff89-76_out -b /public/home/jyli/Public_data/GbV1.fasta -p 10 -L C1,C2, -u merge89_76/merged.gtf C1_R1_SRR1363518_mapping_Gb/accepted_hits.bam,C1_R2_SRR1363519_mapping_Gb/accepted_hits.bam C2_R1_SRR1363516_mapping_Gb/accepted_hits.bam,C2_R2_SRR1363517_mapping_Gb/accepted_hits.bam
