#!/bin/bash
#PBS -N quant
#PBS -l nodes=1:ppn=15
#PBS -o S1.out
#PBS -e S1.err
#PBS -q high
echo--------------`date`----------------------
cd /public/home/jyli/RNAseq_clean/20140320 
for file in S1_R S2_R S3_R S4_R S5_R S6_R S7_R S8_R S9_R
do
~/software/Sailfish-0.6.3-Linux_x86-64/bin/sailfish quant -i /public/home/jyli/Sailfish -l "T=PE:O=><:S=SA" -1 $file$1.fastq -2 $file$2.fastq -o $file_mapping -p 15 -a
done
exit
echo-------------`date`----------------------
