#!/bin/bash
#PBS -N T61
#PBS -l nodes=1:ppn=2
#PBS -o T61.out
#PBS -e T61.err
#PBS -l walltime=240:0:0
#PBS -q batch
cd /public/home/jyli/NCBI_SRA/NJAU_TM-1-RNAseq/Tophat
ID=SRR1695160
/public/home/jyli/software/tophat-2.0.13.Linux_x86_64/tophat2 -p 2 -G /public/home/jyli/Public_data/TM-1/tm_1_v01c01.gene_2k_Raw.gff3 -o ${ID}_mapping_Gh /public/home/jyli/Public_data/TM-1/TM-1 ../clean/${ID}_1.clean.fastq ../clean/${ID}_2.clean.fastq
